apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationdeployment
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          imagePullPolicy: Always
          image: imeshaaa/week9-server:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: mongodb-config
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-secret
          ports:
            - containerPort: 3000
